# Generated by Django 4.0 on 2023-05-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_car_manufacturing_year_remove_part_car_and_more'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeprofile',
            name='parts',
        ),
        migrations.AddField(
            model_name='storebranch',
            name='parts',
            field=models.ManyToManyField(to='parts.Part'),
        ),
    ]
