# Generated by Django 4.0 on 2023-05-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_remove_partreview_part_remove_part_is_available_and_more'),
        ('profiles', '0002_remove_storeprofile_parts_storebranch_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storebranch',
            name='parts',
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='categories',
            field=models.ManyToManyField(to='parts.Category'),
        ),
    ]
