# Generated by Django 4.0 on 2023-05-22 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profiles', '0004_customerprofile_inbox_storeprofile_inbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storeprofile', to='auth.user'),
        ),
    ]
