# Generated by Django 4.0 on 2023-06-25 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_storebranch_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longtitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='storebranch',
            name='address',
        ),
        migrations.RemoveField(
            model_name='storebranch',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='storebranch',
            name='longitude',
        ),
        migrations.AddField(
            model_name='storebranch',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.location'),
        ),
    ]
