# Generated by Django 4.0 on 2023-07-03 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_location_remove_storebranch_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.location'),
        ),
    ]
