# Generated by Django 4.0 on 2023-07-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_customerprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='Tripoli', max_length=250),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='Libya', max_length=250),
        ),
    ]
