# Generated by Django 4.0 on 2023-07-09 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_location_city_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.location'),
        ),
    ]
