# Generated by Django 4.0 on 2023-07-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_customerprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='logo',
            field=models.ImageField(default='avatar.png', upload_to='stores_logos'),
        ),
    ]
