# Generated by Django 4.0 on 2023-07-20 17:52

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inboxes', '0005_alter_messagenotification_receiver_inbx'),
        ('parts', '0004_remove_partreview_part_remove_part_is_available_and_more'),
        ('profiles', '0011_storeprofile_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='avatar.png', upload_to='workshops_logos')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=250)),
                ('facebook', models.EmailField(max_length=254)),
                ('brands', models.ManyToManyField(to='parts.Brand')),
                ('categories', models.ManyToManyField(to='parts.Category')),
                ('inbox', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='inboxes.inbox')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('rating', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.customerprofile')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.workshopprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stores_images')),
                ('Workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.workshopprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50)),
                ('_1st_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('_2nd_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.location')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='profiles.workshopprofile')),
            ],
        ),
    ]
