# Generated by Django 4.0 on 2023-07-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_storeprofile_inbox_alter_workshopprofile_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopbranch',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.location'),
        ),
    ]
