# Generated by Django 4.0 on 2023-08-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_workshopbranch_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='logo',
            field=models.ImageField(default='default_store.png', upload_to='stores_logos'),
        ),
    ]
