# Generated by Django 4.0 on 2023-08-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_storeprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
    ]
