# Generated by Django 4.0 on 2023-08-30 18:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_customerprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
    ]
