# Generated by Django 4.0 on 2023-09-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_alter_customerprofile_phone_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storebranch',
            old_name='_1st_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='workshopbranch',
            old_name='_1st_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='storebranch',
            name='_2nd_number',
        ),
        migrations.RemoveField(
            model_name='workshopbranch',
            name='_2nd_number',
        ),
    ]
