# Generated by Django 4.0 on 2023-10-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_alter_storeprofile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='logo',
            field=models.ImageField(default='default_store.png', upload_to='stores_logos'),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
