# Generated by Django 4.0 on 2023-10-02 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inboxes', '0006_alter_inbox_type'),
        ('profiles', '0023_alter_storeprofile_logo_alter_storeprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meccanicoadmin',
            name='inbox',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inboxes.inbox'),
        ),
        migrations.AlterField(
            model_name='workshopprofile',
            name='logo',
            field=models.ImageField(default='workshops_logos/workshop.png', upload_to='workshops_logos'),
        ),
    ]
