# Generated by Django 4.0 on 2023-10-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_meccanicoadmin_inbox_alter_workshopprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='meccanicoadmin',
            name='logo',
            field=models.ImageField(default='admin.png', upload_to='workshops_logos'),
        ),
    ]
