# Generated by Django 4.0 on 2023-10-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_meccanicoadmin_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meccanicoadmin',
            old_name='logo',
            new_name='image',
        ),
    ]
