# Generated by Django 4.0 on 2023-10-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_rename_logo_meccanicoadmin_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meccanicoadmin',
            name='image',
        ),
    ]
