# Generated by Django 4.0 on 2023-10-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_remove_meccanicoadmin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meccanicoadmin',
            name='image',
            field=models.ImageField(default='admin.png', upload_to=''),
        ),
    ]
