# Generated by Django 4.0 on 2023-10-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_meccanicoadmin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Old')], default=2),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
