# Generated by Django 4.0 on 2023-10-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_storeprofile_status_alter_storeprofile_is_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Old')], default=1),
        ),
    ]
