# Generated by Django 4.0 on 2023-10-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_alter_storeprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopprofile',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Old')], default=1),
        ),
        migrations.AlterField(
            model_name='workshopprofile',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
