# Generated by Django 4.0 on 2023-07-11 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_storeprofile_logo'),
        ('stars_rating', '0002_remove_storestarrating_user_storestarrating_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storestarrating',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_rating', to='profiles.storeprofile'),
        ),
    ]
