# Generated by Django 4.0 on 2023-07-22 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_workshopprofile_workshopreview_workshopimage_and_more'),
        ('stars_rating', '0003_alter_storestarrating_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopStarRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.customerprofile')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_rating', to='profiles.workshopprofile')),
            ],
        ),
    ]
