# Generated by Django 4.0 on 2023-08-02 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_workshopbranch_location'),
        ('stars_rating', '0005_alter_workshopstarrating_workshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstarrating',
            name='user',
        ),
        migrations.AddField(
            model_name='productstarrating',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.customerprofile'),
        ),
    ]
