# Generated by Django 4.0 on 2023-05-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_car_manufacturing_year_remove_part_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
