# Generated by Django 4.0 on 2023-07-17 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inboxes', '0004_alter_messagenotification_receiver_inbx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagenotification',
            name='receiver_inbx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_notification', to='inboxes.inbox'),
        ),
    ]
