# Generated by Django 4.0 on 2023-07-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inboxes', '0005_alter_messagenotification_receiver_inbx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='type',
            field=models.IntegerField(choices=[(1, 'Personal'), (2, 'Store'), (3, 'Workshop')], default=1),
        ),
    ]
