# Generated by Django 4.0 on 2023-10-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inboxes', '0006_alter_inbox_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='type',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Personal'), (2, 'Store'), (3, 'Workshop')], default=1),
        ),
    ]
