# Generated by Django 4.0 on 2023-10-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inboxes', '0007_alter_inbox_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
