# Generated by Django 4.0 on 2023-05-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
