# Generated by Django 4.0 on 2023-05-08 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0003_alter_orderitem_item_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='part',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
