# Generated by Django 4.0 on 2023-06-02 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('profiles', '0006_alter_storebranch_store'),
        ('orders', '0005_alter_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItmesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.customerprofile')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
