# Generated by Django 4.0 on 2023-06-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('profiles', '0006_alter_storebranch_store'),
        ('orders', '0006_orderitmeslist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItmesList',
            new_name='OrderItemsList',
        ),
    ]
