# Generated by Django 4.0 on 2023-06-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0008_alter_orderitemslist_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemslist',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product'),
        ),
    ]
