# Generated by Django 4.0 on 2023-06-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
    ]
