# Generated by Django 4.0 on 2023-06-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Waiting'), (2, 'In Progress'), (3, 'Delivered'), (4, 'Canceled')], default=1),
        ),
    ]
