# Generated by Django 4.0 on 2023-06-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Waiting'), (2, 'In Progress'), (3, 'Delivering'), (4, 'Delivered'), (5, 'Canceled')], default=1),
        ),
    ]
