# Generated by Django 4.0 on 2023-07-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_remove_partreview_part_remove_part_is_available_and_more'),
        ('orders', '0020_remove_workshopreservation_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopreservation',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.car'),
        ),
        migrations.AlterField(
            model_name='workshopreservation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Requested'), (2, 'Confirmed'), (3, 'Done'), (4, 'Canceled')], default=1),
        ),
    ]
