# Generated by Django 4.0 on 2023-07-26 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_storeprofile_inbox_alter_workshopprofile_inbox'),
        ('parts', '0004_remove_partreview_part_remove_part_is_available_and_more'),
        ('orders', '0021_workshopreservation_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopreservation',
            name='categories',
            field=models.ManyToManyField(null=True, to='parts.Category'),
        ),
        migrations.AlterField(
            model_name='workshopreservation',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.workshopbranch'),
        ),
    ]
