# Generated by Django 4.0 on 2023-07-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_remove_partreview_part_remove_part_is_available_and_more'),
        ('orders', '0022_workshopreservation_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopreservation',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='parts.Category'),
        ),
    ]
