# Generated by Django 4.0 on 2023-07-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_workshopreservation_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopreservation',
            name='categories',
        ),
    ]
