# Generated by Django 4.0 on 2023-08-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_workshopreservation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopreservation',
            name='time',
            field=models.DateTimeField(blank=True),
        ),
    ]
