# Generated by Django 4.0 on 2023-08-31 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_alter_customerprofile_phone_num'),
        ('orders', '0029_alter_workshopreservation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(2, 'In Progress'), (3, 'Delivered'), (4, 'Store Canceled')], default=2)),
                ('is_seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StoreOrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Waiting'), (5, 'Customer Canceled')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='customerreservationnotification',
            name='status',
            field=models.IntegerField(choices=[(2, 'Confirmed'), (3, 'Done'), (4, 'Workshop Canceled')], default=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Waiting'), (2, 'In Progress'), (3, 'Delivered'), (4, 'Store Canceled'), (5, 'Customer Canceled')], default=1),
        ),
        migrations.AlterField(
            model_name='workshopreservationnotification',
            name='status',
            field=models.IntegerField(choices=[(1, 'Requested'), (5, 'Customer Canceled')], default=1),
        ),
        migrations.DeleteModel(
            name='OrderNotification',
        ),
        migrations.AddField(
            model_name='storeordernotification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='storeordernotification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_notifications', to='profiles.storeprofile'),
        ),
        migrations.AddField(
            model_name='customerordernotification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='customerordernotification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_notifications', to='profiles.customerprofile'),
        ),
    ]
