# Generated by Django 4.0 on 2023-09-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Waiting'), (2, 'In Progress'), (3, 'En Route'), (4, 'Delivered'), (5, 'Store Canceled'), (6, 'Customer Canceled'), (7, 'Product Unavailable')], default=1),
        ),
    ]
