# Generated by Django 4.0 on 2023-09-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopreservation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
