# Generated by Django 4.0 on 2023-09-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_alter_workshopreservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='products_images/default-image.jpg', upload_to='products_images')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.workshopreservation')),
            ],
        ),
    ]
