# Generated by Django 4.0 on 2023-09-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_reservationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationimage',
            name='image',
            field=models.ImageField(upload_to='reservations_images'),
        ),
    ]
