# Generated by Django 4.0 on 2023-09-25 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_alter_reservationimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationimage',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.workshopreservation'),
        ),
    ]
