# Generated by Django 4.0 on 2023-07-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_image_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_counter',
            field=models.IntegerField(default=0),
        ),
    ]
