# Generated by Django 4.0 on 2023-10-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_workshopprofile_status_and_more'),
        ('products', '0006_product_max_quantity_product_min_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ManyToManyField(to='profiles.StoreBranch'),
        ),
    ]
